spring:
  data:
    elasticsearch:
      cluster-name: xiaolang
      cluster-nodes: 192.168.1.108:9300
#      properties:
#        path:
#          logs: ./elasticsearch/log
#          data: ./elasticsearch/data
      repositories:
        enabled: true
